In [1]:
using Kronecker
using LinearAlgebra
include("functions.jl")

benchmarking (generic function with 1 method)

In [2]:
benchmarking()

In [3]:
function old_data()
    
    N = 7

    A0 = [-2 0 
            0 -1]

    A1 = [0 0 
            0 -0.1]

    A2 = [-2 0 0
            0 -1 0
             0 0 -3]

    A3 = [0 0 0
            0 0 0 
             0 0 -0.1]

    # Real matrices from Jia paper

    A4 = zeros(4, 4)
    A4[1, 2] = 376.9911
    A4[2, 1:3] = [-0.0963 -0.5 -0.0801]
    A4[3, :] = [-0.0480 0 -0.1667 0.1]
    A4[4, 4] = -1

    A5 = zeros(4,4)
    A5[4, 1] = 38.0187
    A5[4, 3] = -95.2560

    tau = 0.01

    M, n = build_M(N, tau, A0, A1)
    
    println(eigvals(A0))
    println(eigvals(A1))
end

old_data (generic function with 1 method)

In [4]:
L = 450e-6
C = 2.5e-3
V_dc = 1200
R = 50

50

In [10]:
E = zeros(4,4)
E[1,1] = L
E[2,2] = C
E[3,3] = L
E[4,4] = C
E

J = zeros(4,4)
J[1,2] = -1
J[2,1] = 1
J[3,4] = -1
J[4,3] = 1
J

B = zeros(4,2)
B[1,1] = V_dc/2
B[3,2] = V_dc/2
B

M = [0
    -1
     0
     1]

N = [0 1/R 0 -1/R]

1×4 Matrix{Float64}:
 0.0  0.02  0.0  -0.02

In [11]:
E_inv = inv(E)
A0 = E_inv*J
A1 = E_inv*M*N

4×4 Matrix{Float64}:
 0.0   0.0  0.0   0.0
 0.0  -8.0  0.0   8.0
 0.0   0.0  0.0   0.0
 0.0   8.0  0.0  -8.0

In [47]:
tau = 1e-3
N = 7

M, n = build_M(N, tau, A0, A1)

([-33000.0 -0.0 … 0.0 0.0; -0.0 -33000.0 … 0.0 0.0; … ; 0.0 0.0 … 0.0 -2222.222222222222; 0.0 8.0 … 400.0 0.0], 4)

In [48]:
print(size(M))
eigs = eigvals(M)

(32, 32)

32-element Vector{ComplexF64}:
    -6762.433328104145 - 3421.5589086820964im
    -6762.433328104145 + 3421.5589086820964im
    -6657.733927706982 + 0.0im
   -6657.7339277069395 + 0.0im
    -6657.733927706831 + 0.0im
   -6175.9495455786455 - 3328.7496406630517im
   -6175.9495455786455 + 3328.7496406630517im
    -6175.949545578616 - 3328.749640663043im
    -6175.949545578616 + 3328.749640663043im
     -6175.94954557858 - 3328.7496406629834im
     -6175.94954557858 + 3328.7496406629834im
    -5734.853351577256 + 0.0im
    -4659.690707222986 - 6906.507095476409im
                       ⋮
    -2342.209821286732 - 11152.97729119599im
    -2342.209821286732 + 11152.97729119599im
    -2335.492783344959 - 11144.141640950136im
    -2335.492783344959 + 11144.141640950136im
   -2335.4927833449583 - 11144.141640950162im
   -2335.4927833449583 + 11144.141640950162im
   -2335.4927833449538 - 11144.14164095016im
   -2335.4927833449538 + 11144.14164095016im
     -4.71209581523064 - 949.3551200483726im


In [49]:
old_A = A0 + A1

4×4 Matrix{Float64}:
   0.0  -2222.22    0.0      0.0
 400.0     -8.0     0.0      8.0
   0.0      0.0     0.0  -2222.22
   0.0      8.0   400.0     -8.0

In [46]:
eigs_old = eigvals(old_A)

4-element Vector{ComplexF64}:
      -7.999999999999986 - 942.775099845604im
      -7.999999999999986 + 942.775099845604im
 -1.2079226507921703e-13 - 942.8090415820635im
 -1.2079226507921703e-13 + 942.8090415820635im

In [ ]:
A0

In [ ]:
A1