In [10]:
function x(k)
    return cos(k*pi/N)
end

x (generic function with 1 method)

In [11]:
function build_c()
    
    c = ones(N+1)
    c[1] = 2
    c[N+1] = 2

    return c
end

build_c (generic function with 1 method)

In [12]:
function build_D(N)
    c = build_c()
    
    D = zeros(N+1, N+1)
    D[1,1] = (2*N^2+1)/6
    D[N+1, N+1] = -(2*N^2+1)/6
    
    for i = 1:N-1
        D[i+1,i+1] = -1/2*(x(i)/(1-x(i)^2))
    end
    
    for i = 0:N, j = 0:N
        if i != j
            D[i+1,j+1] = c[i+1]*(-1)^(i+j)/(c[j+1]*(x(i) - x(j)))
        end
    end

    return D
end

build_D (generic function with 1 method)

In [13]:
function build_M(N, tau, A0, A1)
    
    D = build_D(N)
    
    tau = 0.02
    C = -2*D/tau
    
    C_hat = C[1:N, 1:N+1]
    
    n, null = size(A0)
    eye = Matrix(1.0I, n, n)

    M_temp = kronecker(C_hat, eye)
    
    sec_row = zeros(n, n*(N+1))
    sec_row[1:n, 1:n] = A1
    sec_row[1:n, N*n + 1:(N+1)*n] = A0

    M = [M_temp
             sec_row]
    return M, n
end

build_M (generic function with 1 method)

In [14]:
# Benchmarking from Milano

N = 1

D1 = [0.5 -0.5
        0.5 -0.5]

D1_our = build_D(N)

@assert D1 ≈ D1_our

In [15]:
N = 2

D2 = [1.5 -2 0.5
        0.5 0 -0.5
            -0.5 2 -1.5]

D2_our = build_D(N)

@assert D2 ≈ D2_our

In [16]:
using Kronecker
using LinearAlgebra

N = 7

A0 = [-2 0 
        0 -1]

A1 = [0 0 
        0 -0.1]

A2 = [-2 0 0
        0 -1 0
         0 0 -3]

A3 = [0 0 0
        0 0 0 
         0 0 -0.1]

# Real matrices from Jia paper

A4 = zeros(4, 4)
A4[1, 2] = 376.9911
A4[2, 1:3] = [-0.0963 -0.5 -0.0801]
A4[3, :] = [-0.0480 0 -0.1667 0.1]
A4[4, 4] = -1

A5 = zeros(4,4)
A5[4, 1] = 38.0187
A5[4, 3] = -95.2560

tau = 0.01

M, n = build_M(N, tau, A0, A1)



([-1650.0 -0.0 … 50.0 0.0; -0.0 -1650.0 … 0.0 50.0; … ; 0.0 0.0 … -2.0 0.0; 0.0 -0.1 … 0.0 -1.0], 2)

In [17]:
println("According to Milano, size of M should be N*n x N*n")

s, t = size(M)
println("measured size of M = $s x $t")
measured_N = s/n
prod = measured_N*n

println("N = $N")
println("n = $n")
println("measured_N = $measured_N")
println("measured_N*n = $prod")
println("measured_N*n x measured_N*n = $(measured_N*n) x $(measured_N*n)")


According to Milano, size of M should be N*n x N*n
measured size of M = 16 x 16
N = 7
n = 2
measured_N = 8.0
measured_N*n = 16.0
measured_N*n x measured_N*n = 16.0 x 16.0


In [18]:
size(M)

(16, 16)

In [19]:
eigs = eigvals(M)

16-element Vector{ComplexF64}:
  -332.8866963853495 + 0.0im
  -326.6925313026702 + 0.0im
  -312.6754369714155 - 166.41401274431607im
  -312.6754369714155 + 166.41401274431607im
  -308.7974772789299 - 166.43748203315153im
  -308.7974772789299 + 166.43748203315153im
  -232.9845353611487 - 345.3253547738202im
  -232.9845353611487 + 345.3253547738202im
 -232.11021225832025 - 345.2134650840502im
 -232.11021225832025 + 345.2134650840502im
 -116.81697065113974 - 557.2615512465941im
 -116.81697065113974 + 557.2615512465941im
 -116.77463916724722 - 557.2070820475063im
 -116.77463916724722 + 557.2070820475063im
                -2.0 + 0.0im
 -1.1022289355797015 + 0.0im

In [20]:
println(eigvals(A0))
println(eigvals(A1))

[-2.0, -1.0]
[-0.1, 0.0]


In [21]:
# This a a comment

In [22]:
a = 0

0

In [23]:
L = 450e-6
C = 2.5e-3
V_dc = 1200
R = 50

50

In [32]:
E = zeros(4,4)
E[1,1] = L
E[2,2] = C
E[3,3] = L
E[4,4] = C
E

4×4 Matrix{Float64}:
 0.00045  0.0     0.0      0.0
 0.0      0.0025  0.0      0.0
 0.0      0.0     0.00045  0.0
 0.0      0.0     0.0      0.0025

In [25]:
J = zeros(4,4)
J[1,2] = -1
J[2,1] = 1
J[3,4] = -1
J[4,3] = 1
J

4×4 Matrix{Float64}:
 0.0  -1.0  0.0   0.0
 1.0   0.0  0.0   0.0
 0.0   0.0  0.0  -1.0
 0.0   0.0  1.0   0.0

In [26]:
B = zeros(4,2)
B[1,1] = V_dc/2
B[3,1] = V_dc/2

600.0

In [27]:
M = [0
    -1
     0
     1]

4-element Vector{Int64}:
  0
 -1
  0
  1

In [28]:
N = [0 1/R 0 -1/R]

1×4 Matrix{Float64}:
 0.0  0.02  0.0  -0.02

In [29]:
E_inv = inv(E)
A0 = E_inv*J
A1 = E_inv*M*N

4×4 Matrix{Float64}:
 0.0   0.0  0.0   0.0
 0.0  -8.0  0.0   8.0
 0.0   0.0  0.0   0.0
 0.0   8.0  0.0  -8.0

In [30]:
using Kronecker
using LinearAlgebra

tau = 0.01
N = 7

M, n = build_M(N, tau, A0, A1)

([-1650.0 -0.0 … 0.0 0.0; -0.0 -1650.0 … 0.0 0.0; … ; 0.0 0.0 … 0.0 -2222.222222222222; 0.0 8.0 … 400.0 0.0], 4)

In [31]:
print(size(M))
eigs = eigvals(M)

(32, 32)

32-element Vector{ComplexF64}:
     -347.04166000453813 - 237.42736272291904im
     -347.04166000453813 + 237.42736272291904im
      -332.8866963853593 + 0.0im
      -332.8866963853452 - 8.937034683373284e-13im
      -332.8866963853452 + 8.937034683373284e-13im
      -308.7974772789347 - 166.43748203314763im
      -308.7974772789347 + 166.43748203314763im
      -308.7974772789303 - 166.43748203315502im
      -308.7974772789303 + 166.43748203315502im
     -308.79747727891953 - 166.43748203315454im
     -308.79747727891953 + 166.43748203315454im
      -267.1482540165781 + 0.0im
     -234.13525684792464 - 311.22624223538554im
                         ⋮
     -116.77463916724818 - 557.2070820475064im
     -116.77463916724818 + 557.2070820475064im
     -116.77463916724805 - 557.2070820475077im
     -116.77463916724805 + 557.2070820475077im
      -116.7746391672475 - 557.2070820475071im
      -116.7746391672475 + 557.2070820475071im
      -111.3310956353307 - 555.8092282466363im
      -111.33