In [1]:
using Kronecker
using LinearAlgebra
include("functions.jl")

In [2]:
benchmarking()

In [3]:
function old_data()
    
    N = 7

    A0 = [-2 0 
            0 -1]

    A1 = [0 0 
            0 -0.1]

    A2 = [-2 0 0
            0 -1 0
             0 0 -3]

    A3 = [0 0 0
            0 0 0 
             0 0 -0.1]

    # Real matrices from Jia paper

    A4 = zeros(4, 4)
    A4[1, 2] = 376.9911
    A4[2, 1:3] = [-0.0963 -0.5 -0.0801]
    A4[3, :] = [-0.0480 0 -0.1667 0.1]
    A4[4, 4] = -1

    A5 = zeros(4,4)
    A5[4, 1] = 38.0187
    A5[4, 3] = -95.2560

    tau = 0.01

    M, n = build_M(N, tau, A0, A1)
    
    println(eigvals(A0))
    println(eigvals(A1))
end

old_data (generic function with 1 method)

In [4]:
L = 450e-6
C = 2.5e-3
V_dc = 1200
R = 50

50

In [5]:
E = zeros(4,4)
E[1,1] = L
E[2,2] = C
E[3,3] = L
E[4,4] = C
E

J = zeros(4,4)
J[1,2] = -1
J[2,1] = 1
J[3,4] = -1
J[4,3] = 1
J

B = zeros(4,2)
B[1,1] = V_dc/2
B[3,2] = V_dc/2
B

M = [0
    -1
     0
     1]

N = [0 1/R 0 -1/R]

1×4 Matrix{Float64}:
 0.0  0.02  0.0  -0.02

In [6]:
E_inv = inv(E)
A0 = E_inv*J
A1 = E_inv*M*N

4×4 Matrix{Float64}:
 0.0   0.0  0.0   0.0
 0.0  -8.0  0.0   8.0
 0.0   0.0  0.0   0.0
 0.0   8.0  0.0  -8.0

In [27]:
tau = 100
N = 10

M, n = build_M(N, tau, A0, A1)

([-0.67 -0.0 … -0.0 -0.0; -0.0 -0.67 … -0.0 -0.0; … ; 0.0 0.0 … 0.0 -2222.222222222222; 0.0 8.0 … 400.0 0.0], 4)

In [28]:
print(size(M))
eigs = eigvals(M)

(44, 44)

44-element Vector{ComplexF64}:
  -0.09387869192329064 - 0.017054169009548394im
  -0.09387869192329064 + 0.017054169009548394im
  -0.09383196443875824 - 0.01715658267127967im
  -0.09383196443875824 + 0.01715658267127967im
  -0.09383196443828866 - 0.017156582672216564im
  -0.09383196443828866 + 0.017156582672216564im
  -0.09383196354869103 - 0.017156586850532445im
  -0.09383196354869103 + 0.017156586850532445im
  -0.08648766390663605 - 0.05205923381030466im
  -0.08648766390663605 + 0.05205923381030466im
  -0.08648766260807329 - 0.052059235360153916im
  -0.08648766260807329 + 0.052059235360153916im
  -0.08648766260738547 - 0.052059235360337915im
                       ⋮
  -0.03861338205589845 - 0.19551753272738534im
  -0.03861338205589845 + 0.19551753272738534im
  -0.03861309918639146 - 0.19551796425335297im
  -0.03861309918639146 + 0.19551796425335297im
  -0.03861309918639072 - 0.1955179642533889im
  -0.03861309918639072 + 0.1955179642533889im
  -0.03861309918517858 - 0.1955179642536712i

In [1]:
eps()

2.220446049250313e-16

In [29]:
old_A = A0 + A1

4×4 Matrix{Float64}:
   0.0  -2222.22    0.0      0.0
 400.0     -8.0     0.0      8.0
   0.0      0.0     0.0  -2222.22
   0.0      8.0   400.0     -8.0

In [30]:
eigs_old = eigvals(old_A)

4-element Vector{ComplexF64}:
      -7.999999999999986 - 942.775099845604im
      -7.999999999999986 + 942.775099845604im
 -1.2079226507921703e-13 - 942.8090415820635im
 -1.2079226507921703e-13 + 942.8090415820635im

In [39]:
A_test = [0 -1/L 0 0
        1/C -1/(R*C) 0 1/(R*C)
        0 0 0 -1/L
        0 1/(R*C) 1/C -1/(R*C)]

4×4 Matrix{Float64}:
   0.0  -2222.22    0.0      0.0
 400.0     -8.0     0.0      8.0
   0.0      0.0     0.0  -2222.22
   0.0      8.0   400.0     -8.0

In [40]:
eigvals(A_test)

4-element Vector{ComplexF64}:
      -7.999999999999986 - 942.775099845604im
      -7.999999999999986 + 942.775099845604im
 -1.2079226507921703e-13 - 942.8090415820635im
 -1.2079226507921703e-13 + 942.8090415820635im