In [1]:
using Kronecker
using LinearAlgebra
include("functions.jl")

benchmarking (generic function with 1 method)

In [2]:
benchmarking()

In [4]:
N = 7

A0 = [-2 0 
        0 -1]

A1 = [0 0 
        0 -0.1]

A2 = [-2 0 0
        0 -1 0
         0 0 -3]

A3 = [0 0 0
        0 0 0 
         0 0 -0.1]

# Real matrices from Jia paper

A4 = zeros(4, 4)
A4[1, 2] = 376.9911
A4[2, 1:3] = [-0.0963 -0.5 -0.0801]
A4[3, :] = [-0.0480 0 -0.1667 0.1]
A4[4, 4] = -1

A5 = zeros(4,4)
A5[4, 1] = 38.0187
A5[4, 3] = -95.2560

tau = 0.01

M, n = build_M(N, tau, A0, A1)

([-1650.0 -0.0 … 50.0 0.0; -0.0 -1650.0 … 0.0 50.0; … ; 0.0 0.0 … -2.0 0.0; 0.0 -0.1 … 0.0 -1.0], 2)

In [5]:
size(M)

(16, 16)

In [6]:
eigs = eigvals(M)

16-element Vector{ComplexF64}:
  -332.8866963853495 + 0.0im
  -326.6925313026702 + 0.0im
  -312.6754369714155 - 166.41401274431607im
  -312.6754369714155 + 166.41401274431607im
  -308.7974772789299 - 166.43748203315153im
  -308.7974772789299 + 166.43748203315153im
  -232.9845353611487 - 345.3253547738202im
  -232.9845353611487 + 345.3253547738202im
 -232.11021225832025 - 345.2134650840502im
 -232.11021225832025 + 345.2134650840502im
 -116.81697065113974 - 557.2615512465941im
 -116.81697065113974 + 557.2615512465941im
 -116.77463916724722 - 557.2070820475063im
 -116.77463916724722 + 557.2070820475063im
                -2.0 + 0.0im
 -1.1022289355797015 + 0.0im

In [7]:
println(eigvals(A0))
println(eigvals(A1))

[-2.0, -1.0]
[-0.1, 0.0]


In [8]:
L = 450e-6
C = 2.5e-3
V_dc = 1200
R = 50

50

In [9]:
E = zeros(4,4)
E[1,1] = L
E[2,2] = C
E[3,3] = L
E[4,4] = C
E

4×4 Matrix{Float64}:
 0.00045  0.0     0.0      0.0
 0.0      0.0025  0.0      0.0
 0.0      0.0     0.00045  0.0
 0.0      0.0     0.0      0.0025

In [10]:
J = zeros(4,4)
J[1,2] = -1
J[2,1] = 1
J[3,4] = -1
J[4,3] = 1
J

4×4 Matrix{Float64}:
 0.0  -1.0  0.0   0.0
 1.0   0.0  0.0   0.0
 0.0   0.0  0.0  -1.0
 0.0   0.0  1.0   0.0

In [11]:
B = zeros(4,2)
B[1,1] = V_dc/2
B[3,2] = V_dc/2
B

4×2 Matrix{Float64}:
 600.0    0.0
   0.0    0.0
   0.0  600.0
   0.0    0.0

In [12]:
M = [0
    -1
     0
     1]

4-element Vector{Int64}:
  0
 -1
  0
  1

In [13]:
N = [0 1/R 0 -1/R]

1×4 Matrix{Float64}:
 0.0  0.02  0.0  -0.02

In [14]:
E_inv = inv(E)
A0 = E_inv*J
A1 = E_inv*M*N

4×4 Matrix{Float64}:
 0.0   0.0  0.0   0.0
 0.0  -8.0  0.0   8.0
 0.0   0.0  0.0   0.0
 0.0   8.0  0.0  -8.0

In [15]:
tau = 0.0001
N = 7

M, n = build_M(N, tau, A0, A1)

([-1650.0 -0.0 … 0.0 0.0; -0.0 -1650.0 … 0.0 0.0; … ; 0.0 0.0 … 0.0 -2222.222222222222; 0.0 8.0 … 400.0 0.0], 4)

In [16]:
print(size(M))
eigs = eigvals(M)

(32, 32)

32-element Vector{ComplexF64}:
     -347.04166000453813 - 237.42736272291904im
     -347.04166000453813 + 237.42736272291904im
      -332.8866963853593 + 0.0im
      -332.8866963853452 - 8.937034683373284e-13im
      -332.8866963853452 + 8.937034683373284e-13im
      -308.7974772789347 - 166.43748203314763im
      -308.7974772789347 + 166.43748203314763im
      -308.7974772789303 - 166.43748203315502im
      -308.7974772789303 + 166.43748203315502im
     -308.79747727891953 - 166.43748203315454im
     -308.79747727891953 + 166.43748203315454im
      -267.1482540165781 + 0.0im
     -234.13525684792464 - 311.22624223538554im
                         ⋮
     -116.77463916724818 - 557.2070820475064im
     -116.77463916724818 + 557.2070820475064im
     -116.77463916724805 - 557.2070820475077im
     -116.77463916724805 + 557.2070820475077im
      -116.7746391672475 - 557.2070820475071im
      -116.7746391672475 + 557.2070820475071im
      -111.3310956353307 - 555.8092282466363im
      -111.33